apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-prd
resources:
- ../../base
- hello-prd-ns.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: hello-ccee
      namespace: hello-prd
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: prd